# Generated by Django 4.0.6 on 2022-08-06 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POST_collector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podio_Application',
            fields=[
                ('link', models.CharField(blank=True, max_length=400)),
                ('app_name', models.CharField(blank=True, max_length=400)),
                ('app_id', models.CharField(blank=True, max_length=400, primary_key=True, serialize=False)),
                ('number_of_items', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Podio_Workspace',
            fields=[
                ('space_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('link', models.CharField(blank=True, max_length=400)),
                ('space_name', models.CharField(blank=True, max_length=400)),
                ('archived', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='podio_application',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POST_collector.podio_workspace'),
        ),
    ]
