# Generated by Django 4.0.6 on 2022-08-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST_collector', '0003_podio_workspace_last_updated_on_heroku'),
    ]

    operations = [
        migrations.AddField(
            model_name='podio_application',
            name='type_of_application',
            field=models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom')], default='custom', max_length=10),
        ),
    ]
