# Generated by Django 4.0.6 on 2022-08-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST_collector', '0004_podio_application_type_of_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='podio_application',
            name='last_updated_on_heroku',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
