# Generated by Django 4.0.6 on 2022-08-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST_collector', '0006_podio_hook'),
    ]

    operations = [
        migrations.AddField(
            model_name='podio_workspace',
            name='type_of_workspace',
            field=models.CharField(choices=[('standard', 'Contains Standard'), ('custom', 'Custom WSP')], default='custom', max_length=10),
        ),
    ]
