# Generated by Django 4.0.6 on 2022-08-07 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POST_collector', '0007_podio_workspace_type_of_workspace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podio_item',
            options={},
        ),
        migrations.RemoveField(
            model_name='podio_item',
            name='SPACE',
        ),
        migrations.RemoveField(
            model_name='podio_item',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='podio_item',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='podio_item',
            name='organization_id_sales',
        ),
        migrations.RemoveField(
            model_name='podio_item',
            name='organization_ranking_sales',
        ),
        migrations.RemoveField(
            model_name='podio_item',
            name='organization_sales',
        ),
        migrations.RemoveField(
            model_name='podio_item',
            name='sales_call_date',
        ),
        migrations.RemoveField(
            model_name='podio_item',
            name='space_id',
        ),
        migrations.AddField(
            model_name='podio_item',
            name='app',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='POST_collector.podio_application'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='podio_item',
            name='PARENT',
        ),
        migrations.AddField(
            model_name='podio_item',
            name='PARENT',
            field=models.ManyToManyField(related_name='Parent', to='POST_collector.podio_item'),
        ),
    ]
