# Generated by Django 4.0.6 on 2022-08-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST_collector', '0008_alter_podio_item_options_remove_podio_item_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podio_item',
            name='Podio_Best_Practices',
            field=models.CharField(blank=True, max_length=1600),
        ),
    ]
