# Generated by Django 4.0.6 on 2022-08-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST_collector', '0010_podio_item_old_podio_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='podio_item',
            name='Tilte_clean',
            field=models.CharField(blank=True, max_length=1600),
        ),
    ]
