# Generated by Django 4.0.6 on 2022-08-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST_collector', '0012_rename_tilte_clean_podio_item_title_clean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podio_item',
            name='Title_clean',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
    ]
