# Generated by Django 4.0.5 on 2022-08-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST_collector', '0017_alter_podio_item_constraints_and_assumptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podio_item',
            name='Outcome',
            field=models.CharField(blank=True, max_length=25600),
        ),
    ]
