# Generated by Django 4.0.5 on 2022-08-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST_collector', '0018_alter_podio_item_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podio_item',
            name='Approach',
            field=models.CharField(blank=True, max_length=51200),
        ),
        migrations.AlterField(
            model_name='podio_item',
            name='Constraints_and_assumptions',
            field=models.CharField(blank=True, max_length=51200),
        ),
        migrations.AlterField(
            model_name='podio_item',
            name='Goal',
            field=models.CharField(blank=True, max_length=51200),
        ),
        migrations.AlterField(
            model_name='podio_item',
            name='Notes',
            field=models.CharField(blank=True, max_length=51200),
        ),
        migrations.AlterField(
            model_name='podio_item',
            name='On_hold_cancellation_reason',
            field=models.CharField(blank=True, max_length=51200),
        ),
        migrations.AlterField(
            model_name='podio_item',
            name='Outcome',
            field=models.CharField(blank=True, max_length=51200),
        ),
        migrations.AlterField(
            model_name='podio_item',
            name='Problem_Statement',
            field=models.CharField(blank=True, max_length=51200),
        ),
        migrations.AlterField(
            model_name='podio_item',
            name='Target_result_description',
            field=models.CharField(blank=True, max_length=51200),
        ),
    ]
