# Generated by Django 3.2.8 on 2022-10-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST_collector', '0019_alter_podio_item_approach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podio_item',
            name='File_location',
            field=models.CharField(blank=True, max_length=12800),
        ),
    ]
