# Generated by Django 2.2.9 on 2022-12-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST_collector', '0021_auto_20221002_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podio_application',
            name='type_of_application',
            field=models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom')], default='custom', max_length=400),
        ),
        migrations.AlterField(
            model_name='podio_item',
            name='Approach',
            field=models.CharField(blank=True, max_length=102400),
        ),
        migrations.AlterField(
            model_name='podio_item',
            name='Constraints_and_assumptions',
            field=models.CharField(blank=True, max_length=102400),
        ),
        migrations.AlterField(
            model_name='podio_item',
            name='Goal',
            field=models.CharField(blank=True, max_length=102400),
        ),
        migrations.AlterField(
            model_name='podio_item',
            name='Notes',
            field=models.CharField(blank=True, max_length=102400),
        ),
        migrations.AlterField(
            model_name='podio_item',
            name='On_hold_cancellation_reason',
            field=models.CharField(blank=True, max_length=102400),
        ),
        migrations.AlterField(
            model_name='podio_item',
            name='Outcome',
            field=models.CharField(blank=True, max_length=102400),
        ),
        migrations.AlterField(
            model_name='podio_item',
            name='Problem_Statement',
            field=models.CharField(blank=True, max_length=102400),
        ),
        migrations.AlterField(
            model_name='podio_item',
            name='Target_result_description',
            field=models.CharField(blank=True, max_length=102400),
        ),
    ]
