# Generated by Django 3.1.4 on 2023-01-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST_collector', '0023_auto_20230101_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podio_item',
            name='PARENT',
            field=models.ManyToManyField(blank=True, related_name='_podio_item_PARENT_+', to='POST_collector.Podio_Item'),
        ),
    ]
